### ISSUE TITLE
Undo

### ISSUE THREAD

**Issue by mikelortega** [Roland09/BetterLitShaderExtensions#3]
Hi Roland09, nice work with this tool :)
I missed the option to Undo the conversion, I've added this in line 95 of MaterialUpgrader.cs just before the conversion so it can be undone.
![image](https://user-images.githubusercontent.com/3043173/177297989-fa795ac6-e753-409f-9e3a-639f3c7a1e86.png)
I can create a pull request if you are interested.
Cheers.

**Comment by Roland09** [comment]
Thank you Mikel, I added it.
